CREATE TABLE IF NOT EXISTS tracks (
    id VARCHAR PRIMARY KEY,
    name VARCHAR NOT NULL,
    popularity INT,
    duration_ms INT,
    explicit BOOLEAN,
    artists TEXT,
    id_artists TEXT,
    energy FLOAT,
    key INT,
    loudness FLOAT,
    mode INT,
    speechiness FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    valence FLOAT,
    tempo FLOAT,
    time_signature INT,
    release_year INT,
    release_month INT,
    release_day INT,
    danceability_label VARCHAR,
    artist_followers FLOAT,
    artist_genres TEXT,
    artist_popularity INT
);
